In [ ]:
from google.colab import files
Uploaded=files.upload()

Saving TB_Dataset_encode_clus.xlsx to TB_Dataset_encode_clus.xlsx

In [ ]:
import os
import pandas as pd

In [ ]:
df = pd.read_excel('TB_Dataset_encode_clus.xlsx')

df.head()

,BMI,Gender,Age,ICD10_Group_Chronic_Diseases,ICD10_Group_Lymph_Node_TB,ICD10_Group_Miliary_TB,ICD10_Group_Nervous_System_TB,ICD10_Group_Other_Extrapulmonary_TB,ICD10_Group_Other_Respiratory_TB,ICD10_Group_Pulmonary_TB,...,Take a Co-Trimoxazole,(TB F/U) follow up,position of TB,Chronic Kidney Disease,Chronic Obstructive Pulmonary Disease,Diabetes Mellitus,Liver Disease,AFB resulf of first month,Duration,result
0,14.57,0,73,0,0,0,0,0,0,1,...,0,3,1,0,0,0,0,0,NaN,กำลังรักษา
1,15.94,0,64,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,NaN,กำลังรักษา
2,16.53,0,81,0,0,0,0,0,0,1,...,0,2,1,0,0,0,0,3,NaN,กำลังรักษา
3,20.24,0,41,0,0,0,1,0,0,0,...,0,0,2,0,0,0,0,-1,NaN,กำลังรักษา
4,21.17,1,49,0,0,0,0,0,0,1,...,0,3,1,0,0,0,0,0,NaN,กำลังรักษา

In [ ]:
# แสดงจำนวนแถว
print("Number of rows:", len(df))

Number of rows: 25239

In [ ]:
# แสดงชื่อคอลัมน์ทั้งหมด
print("Columns:", df.columns.tolist())

Columns: ['BMI', 'Gender', 'Age', 'ICD10_Group_Chronic_Diseases', 'ICD10_Group_Lymph_Node_TB', 'ICD10_Group_Miliary_TB', 'ICD10_Group_Nervous_System_TB', 'ICD10_Group_Other_Extrapulmonary_TB', 'ICD10_Group_Other_Respiratory_TB', 'ICD10_Group_Pulmonary_TB', 'ICD10_Group_Unspecified_TB', 'Patients Register Types', 'Cohort of TB', 'HIV', 'Treatment of ARV', 'Take a Co-Trimoxazole', '(TB F/U) follow up', 'position of TB', 'Chronic Kidney Disease', ' Chronic Obstructive Pulmonary Disease', 'Diabetes Mellitus', 'Liver Disease', ' AFB resulf of first month', 'Duration', 'result']

In [ ]:
# ดูจำนวน label
df['result'].value_counts()

result
รักษาครบ                 9765
รักษาหาย                 9037
เสียชีวิต                3199
เปลี่ยนวินิจฉัย          1304
ขาดยา                     752
กำลังรักษา                669
โอนออก                    297
RR/MDR ก่อนเดือนที่ 5     138
ล้มเหลว                    78
Name: count, dtype: int64

In [ ]:
# show data train
print('number of rows :',df.shape[0])
print('number of columns :',df.shape[1])
df.info()
df.head()

# นำออกข้อมูล train
df.to_csv('traindata.csv',index=False)

number of rows : 25239
number of columns : 25
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25239 entries, 0 to 25238
Data columns (total 25 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   BMI                                     25239 non-null  float64
 1   Gender                                  25239 non-null  int64
 2   Age                                     25239 non-null  int64
 3   ICD10_Group_Chronic_Diseases            25239 non-null  int64
 4   ICD10_Group_Lymph_Node_TB               25239 non-null  int64
 5   ICD10_Group_Miliary_TB                  25239 non-null  int64
 6   ICD10_Group_Nervous_System_TB           25239 non-null  int64
 7   ICD10_Group_Other_Extrapulmonary_TB     25239 non-null  int64
 8   ICD10_Group_Other_Respiratory_TB        25239 non-null  int64
 9   ICD10_Group_Pulmonary_TB                25239 non-null  int64
 10  ICD10_Group_Unspecified_TB              25239 non-null  int64
 11  Patients Register Types                 25239 non-null  int64
 12  Cohort of TB                            25239 non-null  int64
 13  HIV                                     25239 non-null  int64
 14  Treatment of ARV                        25239 non-null  int64
 15  Take a Co-Trimoxazole                   25239 non-null  int64
 16  (TB F/U) follow up                      25239 non-null  int64
 17  position of TB                          25239 non-null  int64
 18  Chronic Kidney Disease                  25239 non-null  int64
 19   Chronic Obstructive Pulmonary Disease  25239 non-null  int64
 20  Diabetes Mellitus                       25239 non-null  int64
 21  Liver Disease                           25239 non-null  int64
 22   AFB resulf of first month              25239 non-null  int64
 23  Duration                                23760 non-null  float64
 24  result                                  25239 non-null  object
dtypes: float64(2), int64(22), object(1)
memory usage: 4.8+ MB

In [ ]:
# เช็คจำนวนและเปอร์เซ็นต์ของ Missing Values ในแต่ละคอลัมน์
missing_data = df.isnull().sum()
missing_percent = (df.isnull().sum() / len(df)) * 100

# นำมารวมกันเป็น DataFrame เพื่อให้อ่านง่าย
missing_report = pd.DataFrame({
    'Missing Count': missing_data,
    'Percentage (%)': missing_percent
}).sort_values(by='Missing Count', ascending=False)

# แสดงเฉพาะคอลัมน์ที่มี Missing Values
print("--- Missing Values Report ---")
print(missing_report[missing_report['Missing Count'] > 0])

--- Missing Values Report ---
          Missing Count  Percentage (%)
Duration           1479        5.859979

In [ ]:
def clean_data(df, name="Dataset"):
    print(f"--- Cleaning Report for: {name} ---")
    # 2. เช็คและลบ Missing Values (เปลี่ยนจาก ffill/bfill เป็น dropna)
    missing_rows = df.isnull().any(axis=1).sum()
    if missing_rows > 0:
        print(f"[!] Found {missing_rows} rows with missing values. Dropping them...")
        df = df.dropna()
    else:
        print("[✓] No missing values found.")

    # 3. ลบ Constant Columns
    constant_cols = [col for col in df.columns if df[col].nunique() <= 1]
    if len(constant_cols) > 0:
        print(f"[*] Removing {len(constant_cols)} constant columns: {constant_cols}")
        df = df.drop(columns=constant_cols)
    else:
        print("[✓] No constant columns to remove.")

    print(f"Final shape: {df.shape}\n")
    return df

In [ ]:
dt_after_clean = clean_data(df)

--- Cleaning Report for: Dataset ---
[!] Found 1479 rows with missing values. Dropping them...
[✓] No constant columns to remove.
Final shape: (23760, 25)

In [ ]:
# ดูจำนวน label
dt_after_clean['result'].value_counts()

result
รักษาครบ                 9570
รักษาหาย                 8749
เสียชีวิต                2920
เปลี่ยนวินิจฉัย          1255
ขาดยา                     725
โอนออก                    283
RR/MDR ก่อนเดือนที่ 5     126
ล้มเหลว                    75
กำลังรักษา                 57
Name: count, dtype: int64

In [ ]:
df_after_clean = dt_after_clean[~dt_after_clean['result'].isin(['โอนออก','กำลังรักษา'])]

In [ ]:
print(df_after_clean['result'].value_counts())

result
รักษาครบ                 9570
รักษาหาย                 8749
เสียชีวิต                2920
เปลี่ยนวินิจฉัย          1255
ขาดยา                     725
RR/MDR ก่อนเดือนที่ 5     126
ล้มเหลว                    75
Name: count, dtype: int64

# PHASE **1**

STEP 1 : สร้าง Target

In [ ]:
def create_target(x):

    if x in ['รักษาหาย', 'รักษาครบ']:
        return 0

    elif x in ['เสียชีวิต', 'ขาดยา', 'เปลี่ยนวินิจฉัย', 'ล้มเหลว', 'RR/MDR ก่อนเดือนที่ 5 ']:
        return 1

    else:
        return None

In [ ]:
df_after_clean['target'] = df_after_clean['result'].apply(create_target)

df_after_clean = df_after_clean[df_after_clean['target'].notna()]

/tmp/ipykernel_8970/2427547002.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_after_clean['target'] = df_after_clean['result'].apply(create_target)

In [ ]:
df_after_clean

,BMI,Gender,Age,ICD10_Group_Chronic_Diseases,ICD10_Group_Lymph_Node_TB,ICD10_Group_Miliary_TB,ICD10_Group_Nervous_System_TB,ICD10_Group_Other_Extrapulmonary_TB,ICD10_Group_Other_Respiratory_TB,ICD10_Group_Pulmonary_TB,...,(TB F/U) follow up,position of TB,Chronic Kidney Disease,Chronic Obstructive Pulmonary Disease,Diabetes Mellitus,Liver Disease,AFB resulf of first month,Duration,result,target
1479,19.53,0,59,0,0,0,0,0,0,1,...,1,1,0,0,0,0,-1,231.0,รักษาหาย,0.0
1480,19.12,1,51,0,0,0,0,0,0,1,...,3,1,0,0,0,0,3,128.0,รักษาครบ,0.0
1481,19.41,0,59,0,0,0,0,0,0,1,...,1,1,0,0,0,0,-1,122.0,รักษาครบ,0.0
1483,19.47,0,51,0,0,0,0,0,0,1,...,0,1,0,0,0,0,-1,62.0,เสียชีวิต,1.0
1484,19.12,0,21,0,0,0,0,0,0,1,...,1,1,0,0,0,0,2,60.0,ล้มเหลว,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25229,18.42,0,59,0,0,0,0,0,0,1,...,1,1,0,0,0,0,0,0.0,เสียชีวิต,1.0
25230,17.22,1,83,0,0,0,0,0,0,1,...,1,1,0,0,0,0,0,0.0,เสียชีวิต,1.0
25235,21.45,0,55,0,0,0,0,1,0,0,...,1,2,0,0,0,0,0,0.0,เสียชีวิต,1.0
25236,18.55,1,79,0,0,0,0,0,1,0,...,1,1,0,0,0,0,0,0.0,รักษาครบ,0.0
25237,21.48,0,56,0,0,0,0,0,0,1,...,2,2,0,0,0,0,-1,0.0,รักษาหาย,0.0

In [ ]:
df_after_clean.columns

Index(['BMI', 'Gender', 'Age', 'ICD10_Group_Chronic_Diseases',
       'ICD10_Group_Lymph_Node_TB', 'ICD10_Group_Miliary_TB',
       'ICD10_Group_Nervous_System_TB', 'ICD10_Group_Other_Extrapulmonary_TB',
       'ICD10_Group_Other_Respiratory_TB', 'ICD10_Group_Pulmonary_TB',
       'ICD10_Group_Unspecified_TB', 'Patients Register Types', 'Cohort of TB',
       'HIV', 'Treatment of ARV', 'Take a Co-Trimoxazole',
       '(TB F/U) follow up', 'position of TB', 'Chronic Kidney Disease',
       ' Chronic Obstructive Pulmonary Disease', 'Diabetes Mellitus',
       'Liver Disease', ' AFB resulf of first month', 'Duration', 'result',
       'target'],
      dtype='object')

STEP 2 : สร้าง X Y

In [ ]:
selected_columns = [('BMI', 'Gender', 'Age', 'ICD10_Group_Chronic_Diseases',
       'ICD10_Group_Lymph_Node_TB', 'ICD10_Group_Miliary_TB',
       'ICD10_Group_Nervous_System_TB', 'ICD10_Group_Other_Extrapulmonary_TB',
       'ICD10_Group_Other_Respiratory_TB', 'ICD10_Group_Pulmonary_TB',
       'ICD10_Group_Unspecified_TB', 'Patients Register Types', 'Cohort of TB',
       'HIV', 'Treatment of ARV', 'Take a Co-Trimoxazole',
       '(TB F/U) follow up', 'position of TB', 'Chronic Kidney Disease',
       ' Chronic Obstructive Pulmonary Disease', 'Diabetes Mellitus',
       'Liver Disease', ' AFB resulf of first month', 'Duration')]

In [ ]:
X = df_after_clean[list(selected_columns[0])]
y = df_after_clean['target']

In [ ]:
X

,BMI,Gender,Age,ICD10_Group_Chronic_Diseases,ICD10_Group_Lymph_Node_TB,ICD10_Group_Miliary_TB,ICD10_Group_Nervous_System_TB,ICD10_Group_Other_Extrapulmonary_TB,ICD10_Group_Other_Respiratory_TB,ICD10_Group_Pulmonary_TB,...,Treatment of ARV,Take a Co-Trimoxazole,(TB F/U) follow up,position of TB,Chronic Kidney Disease,Chronic Obstructive Pulmonary Disease,Diabetes Mellitus,Liver Disease,AFB resulf of first month,Duration
1479,19.53,0,59,0,0,0,0,0,0,1,...,0,0,1,1,0,0,0,0,-1,231.0
1480,19.12,1,51,0,0,0,0,0,0,1,...,0,0,3,1,0,0,0,0,3,128.0
1481,19.41,0,59,0,0,0,0,0,0,1,...,0,0,1,1,0,0,0,0,-1,122.0
1483,19.47,0,51,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,-1,62.0
1484,19.12,0,21,0,0,0,0,0,0,1,...,0,0,1,1,0,0,0,0,2,60.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25229,18.42,0,59,0,0,0,0,0,0,1,...,0,0,1,1,0,0,0,0,0,0.0
25230,17.22,1,83,0,0,0,0,0,0,1,...,0,0,1,1,0,0,0,0,0,0.0
25235,21.45,0,55,0,0,0,0,1,0,0,...,0,0,1,2,0,0,0,0,0,0.0
25236,18.55,1,79,0,0,0,0,0,1,0,...,0,0,1,1,0,0,0,0,0,0.0
25237,21.48,0,56,0,0,0,0,0,0,1,...,0,0,2,2,0,0,0,0,-1,0.0

In [ ]:
y

1479     0.0
1480     0.0
1481     0.0
1483     1.0
1484     1.0
        ...
25229    1.0
25230    1.0
25235    1.0
25236    0.0
25237    0.0
Name: target, Length: 23294, dtype: float64

STEP 3 : Split train and test

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

STEP 4 : Train XG

In [ ]:
!pip install xgboost
from xgboost import XGBClassifier

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.30.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

In [ ]:
neg = (y_train == 0).sum()
pos = (y_train == 1).sum()

print(neg / pos)

3.6821608040201004

In [ ]:
model_xg = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    objective='binary:logistic',
    scale_pos_weight=3.6821608040201004,
    random_state=42
)

In [ ]:
model_xg.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)